services:

  web:
    tty: true
    stdin_open: true
    build: .
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    command: >
       gunicorn -c gunicorn.conf.py run:app
    networks:
      - parse_network


networks:
  parse_network:
    driver: bridge
